"""empty message

Revision ID: 315ee87a21b3
Revises: b7263ff6a78c
Create Date: 2026-08-31 21:24:33.525323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315ee87a21b3'
down_revision: Union[str, Sequence[str], None] = 'b7263ff6a78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('common_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('pot_size', sa.String(length=50), nullable=True),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('acquired_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.Enum('HEALTHY', 'ATTENTION', 'STRUGGLE', 'DECEASED', name='healthstatus'), nullable=False),
    sa.Column('watering_frequency', sa.String(length=100), nullable=True),
    sa.Column('sunlight_type', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'DIRECT', name='sunlighttype'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_id'), 'plants', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plants_id'), table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
